project_id = "akmxieztulckunxfttfg"

[functions.process-memo]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.verify-invite-token]
verify_jwt = false

[functions.suggest-icon]
verify_jwt = false

[functions.generate-synthesis]
verify_jwt = false

[functions.generate-axes]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-transmission-email]
verify_jwt = false

[functions.verify-access-code]
verify_jwt = false


[functions.debug-copy]
verify_jwt = false
