import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const allowedOrigins = [
  "https://the-village.app",
  "https://thevillage-app.lovable.app",
];

function getCorsHeaders(req: Request) {
  const origin = req.headers.get("origin") || "";
  const corsOrigin = allowedOrigins.includes(origin) ? origin : allowedOrigins[0];
  return {
    "Access-Control-Allow-Origin": corsOrigin,
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
  };
}

Deno.serve(async (req) => {
  const corsHeaders = getCorsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Verify caller
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUser = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: userError } = await supabaseUser.auth.getUser();
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userId = user.id;

    const { email, role, enfant_id } = await req.json();

    if (!email || !enfant_id) {
      return new Response(JSON.stringify({ error: "email and enfant_id are required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Admin client
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Check caller is owner or coparent
    const { data: membership } = await supabaseAdmin
      .from("enfant_membres")
      .select("role")
      .eq("enfant_id", enfant_id)
      .eq("user_id", userId)
      .single();

    if (!membership || !["owner", "coparent"].includes(membership.role)) {
      return new Response(JSON.stringify({ error: "Not authorized to invite" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Insert invitation — token is auto-generated by DB default
    const { data: invitation, error: inviteDbError } = await supabaseAdmin
      .from("invitations")
      .insert({
        enfant_id,
        invited_by: userId,
        email,
        role: role || "coparent",
      })
      .select("token")
      .single();

    if (inviteDbError || !invitation) {
      console.error("Insert invitation error:", inviteDbError);
      return new Response(JSON.stringify({ error: "Failed to create invitation" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Fetch enfant prénom for email
    const { data: enfant } = await supabaseAdmin
      .from("enfants")
      .select("prenom")
      .eq("id", enfant_id)
      .single();

    const prenomEnfant = enfant?.prenom || "votre enfant";

    // Fetch inviter display name
    const inviterName = user.user_metadata?.full_name || user.email || "Un membre du Village";

    // Send email via Resend
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      console.error("RESEND_API_KEY not configured");
      return new Response(JSON.stringify({ error: "Email service not configured" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const inviteLink = `https://thevillage-app.lovable.app/onboarding-invite?token=${invitation.token}`;

    const emailHtml = `
<!DOCTYPE html>
<html lang="fr">
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#F9EDE8;font-family:'Helvetica Neue',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F9EDE8;padding:40px 20px;">
    <tr><td align="center">
      <table width="480" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:20px;padding:40px;box-shadow:0 4px 24px rgba(139,116,224,0.08);">
        <tr><td align="center" style="padding-bottom:24px;">
          <div style="width:56px;height:56px;border-radius:50%;background:linear-gradient(135deg,#E8736A,#8B74E0);display:inline-flex;align-items:center;justify-content:center;">
            <span style="font-size:28px;">🏡</span>
          </div>
        </td></tr>
        <tr><td align="center" style="padding-bottom:16px;">
          <h1 style="margin:0;font-size:22px;color:#1E1A1A;font-weight:600;">
            Rejoignez le Village de ${prenomEnfant}
          </h1>
        </td></tr>
        <tr><td align="center" style="padding-bottom:32px;">
          <p style="margin:0;font-size:15px;color:#9A9490;line-height:1.6;max-width:380px;">
            ${inviterName} vous invite à suivre le parcours de ${prenomEnfant}. 
            Ensemble, vous pourrez coordonner le suivi et partager les observations au quotidien.
          </p>
        </td></tr>
        <tr><td align="center" style="padding-bottom:32px;">
          <a href="${inviteLink}" style="display:inline-block;padding:14px 40px;background:linear-gradient(135deg,#E8736A,#8B74E0);color:#ffffff;text-decoration:none;border-radius:14px;font-size:15px;font-weight:500;box-shadow:0 6px 20px rgba(139,116,224,0.35);">
            Rejoindre le Village →
          </a>
        </td></tr>
        <tr><td align="center">
          <p style="margin:0;font-size:12px;color:#C4BEB8;line-height:1.5;">
            Ce lien expire dans 7 jours.<br>
            Si vous n'êtes pas à l'origine de cette demande, ignorez cet email.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "The Village <noreply@the-village.app>",
        to: [email],
        subject: `Rejoignez le Village de ${prenomEnfant}`,
        html: emailHtml,
      }),
    });

    if (!resendRes.ok) {
      const resendError = await resendRes.text();
      console.error("Resend API error:", resendRes.status, resendError);
      return new Response(JSON.stringify({ error: "Failed to send invitation email" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("invite-member error:", err);
    return new Response(JSON.stringify({ error: "Internal server error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
